version: '3.8'

services:
  pulse-power-app:
    image: duccuong1609/pulse-power-app:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
